-- ==========================================================================
-- FLRP :: flrp_spawn/config.lua — spawn selector points
-- ==========================================================================
-- Each point: name, coords vector4(x, y, z, heading), and an optional `ace`.
-- When `ace` is set, only players whose principal holds that ace may spawn
-- there (checked SERVER-SIDE in server.lua). `flrp.leo` = any sworn BSO/FHP/MPD
-- member (see config/permissions.cfg). Use flrp.dept.bso/fhp/mpd for one dept.
-- ==========================================================================
Config = Config or {}

-- ---- Banner / header (top of the selector) -------------------------------
Config.Header = {
  title    = 'FLRP',                       -- big bold word
  subtitle = 'SPAWN SELECTOR',             -- cyan accent word
  -- Two-line blurb under the title.
  blurb    = 'Choose where to drop in, or return to where you last logged off.',
  -- Right-hand block under the player name. No economy on FLRP, so this is a
  -- community tag rather than a cash balance (edit freely).
  tagline  = 'Florida Roleplay',
}

-- Each point: name (big label), area (small label under it), coords
-- vector4(x, y, z, heading), optional `ace` gate, and — new for the card UI —
-- an optional `desc` (shown in the Information box) and `image` (the card
-- background). Images below point at the bundled location art in the resource
-- img/ folder (generated by tools/gen-art.mjs — re-run it to tweak them). The
-- path is relative to the NUI page (html/index.html), hence the '../img/'.
-- You can also swap in your own '../img/foo.png' or any external https URL.
-- Leave `image` nil to fall back to a glass card showing the live in-game
-- location behind it.
Config.Points = {
  { name = 'Downtown Miami', area = 'Miami-Dade',     image = '../img/legion.webp',     desc = 'Bayfront core — banks, shops and the busiest civilian hub.',        coords = vector4(197.94, -932.4, 30.69, 320.0) },
  { name = 'Jackson Memorial', area = 'Miami-Dade',   image = '../img/pillbox.jpg',     desc = 'Civic Center medical district beside Jackson Memorial Hospital.',                coords = vector4(298.98, -584.45, 43.26, 70.0) },
  { name = 'Miami International', area = 'Miami-Dade', image = '../img/airport.webp',   desc = 'MIA — air ops, cargo and the Dolphin Expressway.',      coords = vector4(-1037.74, -2738.04, 20.17, 330.0) },
  { name = 'Miami PD Headquarters', area = 'MPD — LEO only', image = '../img/missionrow.webp', desc = 'Miami Police Department headquarters. Sworn law enforcement only.',           coords = vector4(440.83, -984.53, 22.85, 268.2), ace = 'flrp.leo' },
  { name = 'BSO Davie District', area = 'BSO — LEO only', image = '../img/sandyshores.webp', desc = 'Broward Sheriff\'s Office district station in Davie. Sworn law enforcement only.', coords = vector4(1850.71, 3700.96, 33.76, 291.4), ace = 'flrp.leo' },
  { name = 'FHP Troop E', area = 'FHP — LEO only', image = '../img/grapeseed.webp', desc = 'Florida Highway Patrol Troop E station. Sworn law enforcement only.', coords = vector4(2821.90, 4763.21, 47.37, 78.8), ace = 'flrp.leo' },
  { name = 'Davie',          area = 'Broward County', image = '../img/sandyshores.webp',desc = 'Western Broward town — ranches, the rodeo grounds and the BSO district.',       coords = vector4(1884.41, 3714.45, 32.93, 210.0) },
  { name = 'Deerfield Beach', area = 'Broward County', image = '../img/paleto.jpg',     desc = 'The far-north coastal town — the pier, the beach and the bank.',               coords = vector4(-134.20, 6212.20, 31.21, 47.09) },
  { name = 'Homestead',      area = 'South Dade',     image = '../img/grapeseed.webp',  desc = 'Quiet farming community in the Redland — nurseries and packing houses.',                    coords = vector4(1654.72, 4825.46, 42.08, 280.0) },
  { name = 'Coral Gables',   area = 'Miami-Dade',     image = '../img/vinewood.webp',   desc = 'Tree-lined estates, Miracle Mile and old-money mansions.',          coords = vector4(436.64, 218.38, 103.62, 160.0) },
  { name = 'South Beach',    area = 'Miami Beach',    image = '../img/delperro.jpg',    desc = 'Ocean Drive — the beachfront, the pier and the boardwalk.',                 coords = vector4(-1341.27, -1298.66, 4.84, 292.0) },
  { name = 'Coconut Grove',  area = 'Miami-Dade',     image = '../img/mirrorpark.webp', desc = 'Leafy bayside neighbourhood — marinas, cafés and quiet streets.',              coords = vector4(1130.21, -645.9, 56.58, 272.0) },
}

-- Preview camera: when a card is focused, the camera flies to that spawn and
-- the real location renders behind the (translucent) cards. Tune the framing
-- here, or override per-point with a `preview = { dist=, height=, fov= }` field.
--   dist   : metres the camera sits back from the spawn (along its heading)
--   height : metres above the spawn
--   fov    : field of view (lower = more zoomed in)
--   interp : ms to glide between locations as you move across cards
Config.Preview = {
  dist   = 20.0,
  height = 10.0,
  fov    = 50.0,
  interp = 900,
}

-- Banner logo (top-left). Bundled locally so it never depends on the website
-- being up; swap the file in img/ or point this at any https URL instead.
Config.LogoUrl = '../img/flrp-logo.png'

-- ---- Respawn behaviour ----------------------------------------------------
-- When a player dies, bring them back to THIS selector instead of the vanilla
-- "wasted" → nearest-hospital respawn. The selector revives them in place
-- (hidden) first so the engine's own respawn doesn't fight it. Set false to
-- restore default GTA respawn (e.g. once an EMS/downed system is added).
Config.RespawnToSelector = true
-- How long (ms) to let the death play out before the selector reopens.
Config.RespawnDelay = 3000
