-- ==========================================================================
-- FLRP :: flrp_spawn/config.lua — spawn selector points
-- ==========================================================================
-- Each point: name, coords vector4(x, y, z, heading), and an optional `ace`.
-- When `ace` is set, only players whose principal holds that ace may spawn
-- there (checked SERVER-SIDE in server.lua). `flrp.leo` = any sworn BSO/FHP/MPD
-- member (see config/permissions.cfg). Use flrp.dept.bso/fhp/mpd for one dept.
-- ==========================================================================
Config = Config or {}

-- ---- Banner / header (top of the selector) -------------------------------
Config.Header = {
  title    = 'FLRP',                       -- big bold word
  subtitle = 'SPAWN SELECTOR',             -- cyan accent word
  -- Two-line blurb under the title.
  blurb    = 'Choose where to drop in, or return to where you last logged off.',
  -- Right-hand block under the player name. No economy on FLRP, so this is a
  -- community tag rather than a cash balance (edit freely).
  tagline  = 'Florida Roleplay',
}

-- Each point: name (big label), area (small label under it), coords
-- vector4(x, y, z, heading), optional `ace` gate, and — new for the card UI —
-- an optional `desc` (shown in the Information box) and `image` (the card
-- background). Images below point at the bundled location art in the resource
-- img/ folder (generated by tools/gen-art.mjs — re-run it to tweak them). The
-- path is relative to the NUI page (html/index.html), hence the '../img/'.
-- You can also swap in your own '../img/foo.png' or any external https URL.
-- Leave `image` nil to fall back to a glass card showing the live in-game
-- location behind it.
Config.Points = {
  { name = 'Legion Square',  area = 'Los Santos',     image = '../img/legion.webp',     desc = 'Downtown core — banks, shops and the busiest civilian hub.',        coords = vector4(197.94, -932.4, 30.69, 320.0) },
  { name = 'Pillbox Hill',   area = 'Los Santos',     image = '../img/pillbox.jpg',     desc = 'Central medical district next to Pillbox Hospital.',                coords = vector4(298.98, -584.45, 43.26, 70.0) },
  { name = 'LS Airport',     area = 'Los Santos',     image = '../img/airport.svg',     desc = 'Los Santos International — air ops and the southern highway.',      coords = vector4(-1037.74, -2738.04, 20.17, 330.0) },
  { name = 'Mission Row PD', area = 'MPD — LEO only',  image = '../img/missionrow.svg',  desc = 'Mission Row police station. Sworn law enforcement only.',           coords = vector4(428.23, -984.28, 30.71, 0.0), ace = 'flrp.leo' },
  { name = 'Sandy Shores',   area = 'Blaine County',  image = '../img/sandyshores.svg', desc = 'Desert town in the county — Sandy SO and the trailer parks.',       coords = vector4(1884.41, 3714.45, 32.93, 210.0) },
  { name = 'Paleto Bay',     area = 'Blaine County',  image = '../img/paleto.jpg',      desc = 'The far-north coastal town, Paleto SO and the bank.',               coords = vector4(-134.20, 6212.20, 31.21, 47.09) },
  { name = 'Grapeseed',      area = 'Blaine County',  image = '../img/grapeseed.webp',  desc = 'Quiet farming community east of the Alamo Sea.',                    coords = vector4(1654.72, 4825.46, 42.08, 280.0) },
  { name = 'Vinewood',       area = 'Los Santos',     image = '../img/vinewood.webp',   desc = 'The hills above the city — clubs, mansions and the sign.',          coords = vector4(436.64, 218.38, 103.62, 160.0) },
  { name = 'Del Perro',      area = 'Los Santos',     image = '../img/delperro.jpg',    desc = 'West-side beachfront, the pier and the boardwalk.',                 coords = vector4(-1341.27, -1298.66, 4.84, 292.0) },
  { name = 'Mirror Park',    area = 'Los Santos',     image = '../img/mirrorpark.webp', desc = 'East-side residential neighbourhood around the lake.',              coords = vector4(1130.21, -645.9, 56.58, 272.0) },
}

-- Preview camera: when a card is focused, the camera flies to that spawn and
-- the real location renders behind the (translucent) cards. Tune the framing
-- here, or override per-point with a `preview = { dist=, height=, fov= }` field.
--   dist   : metres the camera sits back from the spawn (along its heading)
--   height : metres above the spawn
--   fov    : field of view (lower = more zoomed in)
--   interp : ms to glide between locations as you move across cards
Config.Preview = {
  dist   = 20.0,
  height = 10.0,
  fov    = 50.0,
  interp = 900,
}

Config.LogoUrl = 'https://www.flrp.us/images/c8452f76261f8e9c.png'
