#!/usr/bin/env bash
# ==========================================================================
# FLRP :: deploy/assemble.sh — assemble content repos into the server
# ==========================================================================
# Clones/pulls each content repo listed in content-repos.manifest into the
# correct bracketed resources folder, then regenerates config/content.cfg so
# the server `ensure`s them. Idempotent: re-run any time to update content.
#
# This is the SSRP-style multi-repo assembly. The CORE repo (flrp-server) is
# this checkout; CONTENT repos (vehicles/eup/maps/departments) are separate,
# independently-permissioned repos. See docs/REPOSITORY_STRATEGY.md.
#
# Usage:
#   deploy/assemble.sh [--manifest FILE] [--dry-run]
#
# Notes:
#   * Content is cloned to server-data/resources/[<category>]/[<repo-name>]/
#     (bracketed) — invisible to the core repo (.gitignore [<category>]/*/)
#     and discovered by FiveM as a resource group.
#   * Never touches config/secrets.cfg.
#   * Each content repo MAY ship a `content.cfg` at its root containing the
#     `ensure <resource>` lines for what it provides; those are exec'd via the
#     generated config/content.cfg. If absent, FiveM still discovers the
#     resources but you must `ensure` them elsewhere.
# ==========================================================================
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1
ROOT="$(pwd)"

MANIFEST="deploy/content-repos.manifest"
DRY=0
while [[ $# -gt 0 ]]; do
  case "$1" in
    --manifest) MANIFEST="$2"; shift 2 ;;
    --dry-run) DRY=1; shift ;;
    *) echo "usage: $0 [--manifest FILE] [--dry-run]"; exit 1 ;;
  esac
done

if [[ ! -f "$MANIFEST" ]]; then
  echo "ERROR: manifest '$MANIFEST' not found."
  echo "       cp deploy/content-repos.manifest.example deploy/content-repos.manifest"
  exit 1
fi

RES="server-data/resources"
GEN="server-data/config/content.cfg"
declare -a CFG_EXECS=()
status=0

category_dir() {
  case "$1" in
    vehicles)    echo "[vehicles]" ;;
    maps)        echo "[maps]" ;;
    eup)         echo "[eup]" ;;
    standalone)  echo "[standalone]" ;;
    departments) echo "[departments]" ;;
    *) echo "" ;;
  esac
}

run() { if [[ $DRY -eq 1 ]]; then echo "DRY: $*"; else eval "$@"; fi; }

echo "==> Assembling content from $MANIFEST"
while read -r category name url branch _rest; do
  # skip comments / blank lines
  [[ -z "${category:-}" || "${category:0:1}" == "#" ]] && continue

  catdir="$(category_dir "$category")"
  if [[ -z "$catdir" ]]; then
    echo "  ! unknown category '$category' for '$name' — skipping"; status=1; continue
  fi
  if [[ "$url" == *REPLACE* ]]; then
    echo "  ! placeholder URL for '$name' — edit the manifest — skipping"; status=1; continue
  fi

  target="$RES/$catdir/[$name]"
  mkdir -p "$RES/$catdir"

  if [[ -d "$target/.git" ]]; then
    echo "  - pull  $category/$name"
    run "git -C '$target' fetch --prune origin" || status=1
    if [[ -n "${branch:-}" && "${branch:0:1}" != "#" ]]; then
      run "git -C '$target' checkout '$branch'" || true
      run "git -C '$target' pull --ff-only origin '$branch'" || status=1
    else
      run "git -C '$target' pull --ff-only" || status=1
    fi
  else
    if [[ -e "$target" && -n "$(ls -A "$target" 2>/dev/null)" ]]; then
      echo "  ! '$target' exists and is not a git repo — skipping (remove it to re-clone)"; status=1; continue
    fi
    echo "  - clone $category/$name"
    if [[ -n "${branch:-}" && "${branch:0:1}" != "#" ]]; then
      run "git clone --branch '$branch' '$url' '$target'" || { status=1; continue; }
    else
      run "git clone '$url' '$target'" || { status=1; continue; }
    fi
  fi

  # Collect a content.cfg fragment if the repo ships one.
  if [[ -f "$target/content.cfg" ]]; then
    CFG_EXECS+=("exec \"resources/$catdir/[$name]/content.cfg\"")
  fi
done < "$MANIFEST"

# Regenerate config/content.cfg (exec'd by server.cfg).
if [[ $DRY -eq 0 ]]; then
  {
    echo "# AUTO-GENERATED by deploy/assemble.sh — do not edit by hand."
    echo "# Execs each content repo's own content.cfg (ensure lines)."
    echo "# Regenerate: deploy/assemble.sh"
    for line in "${CFG_EXECS[@]}"; do echo "$line"; done
  } > "$GEN"
  echo "==> Wrote $GEN (${#CFG_EXECS[@]} content cfg fragment(s))"
else
  echo "DRY: would write $GEN with ${#CFG_EXECS[@]} fragment(s)"
fi

echo
[[ $status -eq 0 ]] && echo "ASSEMBLE: OK" || echo "ASSEMBLE: completed with warnings (see above)"
exit $status
