#!/usr/bin/env bash
# ==========================================================================
# FLRP :: tools/new_content_repo.sh — scaffold a content repo skeleton
# ==========================================================================
# Creates a starter directory for a new FLRP CONTENT repo (vehicles / eup /
# maps / departments / standalone) that you then push to Gitea/GitHub as its
# own repo. See docs/REPOSITORY_STRATEGY.md.
#
# Usage:
#   tools/new_content_repo.sh <repo-name> <category> [out-dir]
# Example:
#   tools/new_content_repo.sh flrp-vehicles vehicles ../flrp-vehicles
#
# It does NOT create the remote repo or push — you do that after review.
# ==========================================================================
set -euo pipefail

NAME="${1:?usage: new_content_repo.sh <repo-name> <category> [out-dir]}"
CATEGORY="${2:?usage: new_content_repo.sh <repo-name> <category> [out-dir]}"
OUT="${3:-../$NAME}"

case "$CATEGORY" in
  vehicles|eup|maps|departments|standalone) ;;
  *) echo "ERROR: category must be one of: vehicles eup maps departments standalone"; exit 1 ;;
esac

if [[ -e "$OUT" ]]; then echo "ERROR: '$OUT' already exists"; exit 1; fi
mkdir -p "$OUT"
cd "$OUT"

cat > README.md <<EOF
# $NAME

FLRP **content** repo (category: \`$CATEGORY\`). Assembled into the server at
\`server-data/resources/[$CATEGORY]/[$NAME]/\` by \`deploy/assemble.sh\` in the
core \`flrp-server\` repo. See that repo's \`docs/REPOSITORY_STRATEGY.md\`.

## Layout

Put each resource in its own folder at the repo root, e.g.:

\`\`\`
$NAME/
  some_resource/
    fxmanifest.lua
    ...
  content.cfg        # ensure lines for what this repo provides
\`\`\`

## Rules

- Register vehicles/weapons in the FLRP **database registries** (via the FLRP
  Manager or \`flrp_vehicles:RegisterVehicle\`) — the registry, not hardcoded
  Lua, decides permissions/prices. See the core repo's \`docs/VEHICLES.md\`.
- Never commit escrowed/paid \`.fxap\` assets or secrets.
- \`main\` is protected: work on branches, open PRs, get a CODEOWNERS review.
EOF

cat > content.cfg <<EOF
# ==========================================================================
# $NAME :: content.cfg — ensure lines for this content repo
# ==========================================================================
# Exec'd by the core server via config/content.cfg (regenerated by
# deploy/assemble.sh). List every resource this repo provides.
# ==========================================================================

# ensure some_resource
# ensure another_resource
EOF

cat > CODEOWNERS <<EOF
# CODEOWNERS for $NAME — REPLACE placeholder teams with real Gitea/GitHub teams.
*   @FLRP/${CATEGORY}-team @FLRP/leads
EOF

cat > .gitignore <<'EOF'
# Escrowed / paid resource caches — never commit
*.fxap
# OS / editor
.DS_Store
Thumbs.db
*.swp
EOF

: > .keep

echo "Scaffolded '$NAME' (category: $CATEGORY) at: $OUT"
echo "Next:"
echo "  1) cd $OUT && git init && git add -A && git commit -m 'Initial $NAME scaffold'"
echo "  2) create the empty repo in Gitea/GitHub, add the team + main protection"
echo "     (deploy/gitea_branch_protection.sh in the core repo)"
echo "  3) git remote add origin <url> && git push -u origin main"
echo "  4) add a line to deploy/content-repos.manifest in flrp-server, run deploy/assemble.sh"
